
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp-saldin_development
test:
  <<: *default
  database: myapp-saldin_test

production:
  <<: *default
  database: myapp-saldin_production
  username: myapp-saldin
  password: <%= ENV['MYAPP-SALDIN_DATABASE_PASSWORD'] %>
